#!/usr/bin/env python3
"""Build the secondary legal-reference corpus from the supplied HTML study.

The PDF law remains the primary source and is represented by manually verified,
page-indexed summaries in ``lib/legal-assistant.ts``. The supplied PDF uses a
custom glyph encoding that does not yield dependable Arabic text extraction, so
this script only validates its page count and fingerprint. The HTML document is
plain Arabic and is ingested as an explicitly labelled interpretive source.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
from html.parser import HTMLParser
from pathlib import Path

from pypdf import PdfReader


class ParagraphExtractor(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self._depth = 0
        self._current: list[str] = []
        self.paragraphs: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag == "p":
            if self._depth == 0:
                self._current = []
            self._depth += 1
        elif tag == "br" and self._depth:
            self._current.append("\n")

    def handle_endtag(self, tag: str) -> None:
        if tag != "p" or not self._depth:
            return
        self._depth -= 1
        if self._depth == 0:
            value = "".join(self._current)
            value = re.sub(r"[ \t]+", " ", value)
            value = re.sub(r"\n{2,}", "\n", value).strip()
            if value:
                self.paragraphs.append(value)

    def handle_data(self, data: str) -> None:
        if self._depth:
            self._current.append(data)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def split_text(value: str, target: int = 920) -> list[str]:
    lines = [line.strip() for line in value.splitlines() if line.strip()]
    units: list[str] = []
    for line in lines:
        units.extend(part.strip() for part in re.split(r"(?<=[.؟:])\s+", line) if part.strip())
    chunks: list[str] = []
    current = ""
    for unit in units:
        candidate = f"{current} {unit}".strip()
        if current and len(candidate) > target:
            chunks.append(current)
            current = unit
        else:
            current = candidate
    if current:
        chunks.append(current)
    return [chunk for chunk in chunks if len(chunk) >= 120]


def article_refs(value: str) -> str:
    numbers = set(re.findall(r"المادة\s*/?\s*\(?([0-9]{1,2})", value))
    numbers.update(re.findall(r"مادة\s*/\s*([0-9]{1,2})", value))
    numbers = sorted(numbers, key=int)
    return "المواد " + "، ".join(numbers) if numbers else "دراسة التفعيل"


def keywords(value: str) -> list[str]:
    stop = {
        "الى", "إلى", "على", "عن", "في", "من", "هذا", "هذه", "ذلك", "التي",
        "الذي", "وقد", "كما", "بما", "تم", "إن", "ان", "أو", "او", "ولا", "كل",
    }
    words = re.findall(r"[\u0600-\u06FF]{3,}", value)
    ranked: list[str] = []
    for word in words:
        clean = word.strip("ـ")
        if clean in stop or clean in ranked:
            continue
        ranked.append(clean)
        if len(ranked) == 18:
            break
    return ranked


def ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pdf", type=Path, required=True)
    parser.add_argument("--html", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    pdf_pages = len(PdfReader(str(args.pdf)).pages)
    if pdf_pages != 18:
        raise SystemExit(f"Expected the supplied law scan to contain 18 pages, found {pdf_pages}.")

    extractor = ParagraphExtractor()
    extractor.feed(html.unescape(args.html.read_text(encoding="utf-8", errors="strict")))
    relevant = [
        paragraph for paragraph in extractor.paragraphs
        if "قانون مؤسسة الشهداء رقم (2) لسنة 2016" in paragraph
    ]
    if not relevant:
        raise SystemExit("No relevant legal-study paragraphs were found in the supplied HTML file.")

    raw_chunks: list[str] = []
    for paragraph in relevant:
        raw_chunks.extend(split_text(paragraph))

    source_name = "دراسة مجلس القضاء الأعلى بشأن تفعيل قانون مؤسسة الشهداء رقم (2) لسنة 2016"
    lines = [
        "// Generated by scripts/build-legal-reference-corpus.py; do not edit by hand.",
        'import type { LegalKnowledgeChunk } from "./legal-assistant";',
        "",
        "export const legalSourceManifest = {",
        f"  primaryLaw: {{ file: {ts_string(args.pdf.name)}, pages: {pdf_pages}, sha256: {ts_string(sha256(args.pdf))} }},",
        f"  interpretiveStudy: {{ file: {ts_string(args.html.name)}, sha256: {ts_string(sha256(args.html))} }},",
        f"  generatedChunkCount: {len(raw_chunks)},",
        "} as const;",
        "",
        "export const legalReferenceChunks: LegalKnowledgeChunk[] = [",
    ]
    for index, chunk in enumerate(raw_chunks, start=1):
        refs = article_refs(chunk)
        lines.extend([
            "  {",
            f'    id: "SJC-2019-{index:02d}",',
            f"    article: {ts_string(refs)},",
            '    clause: "دراسة تطبيقية",',
            '    titleAr: "مدى تفعيل أحكام القانون لدى مجلس القضاء الأعلى",',
            f"    textAr: {ts_string(chunk)},",
            '    sourcePage: "HTML",',
            f"    sourceFile: {ts_string(source_name)},",
            '    sourceKind: "interpretive_study",',
            f"    keywords: {json.dumps(keywords(chunk), ensure_ascii=False)},",
            "  },",
        ])
    lines.extend(["];"])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({
        "pdf_pages": pdf_pages,
        "html_paragraphs": len(relevant),
        "generated_chunks": len(raw_chunks),
        "output": str(args.output),
    }, ensure_ascii=True))


if __name__ == "__main__":
    main()
